### ISSUE TITLE
Restructuration

### ISSUE THREAD

**Issue by jetelain** [Braini01/bis-file-formats#5]
Hi,

I've made a fork with a lot of improvements on wrp files manipulation, I would like to make a PR, but I've restructured everything in a single assembly to make it easier to publish on nuget.org (eg. having a single package to publish). It fits in a 100 Kb assembly.

I would like to know if you're OK about that, or would you like to keep everything in really small assemblies ?

(Fork => https://github.com/jetelain/bis-file-formats).

Best regards,

**Comment by Braini01** [comment]
I probably would prefer smaller assemblies and packages personally, but I am even more prefering contributions :)

**Comment by jetelain** [comment]
I'm ok with that : I've left everything in multiple assemblies and made a PR #6
